#!/usr/bin/env python3
"""
Seed de editais reais — O Tutor
Popula ~45 editais reais na tabela editais via Supabase REST API.
Não requer dependências externas além da stdlib Python.

Uso:
  cd estudei-app
  python scripts/seed_editais.py
"""
import json, os, urllib.request, urllib.error
from datetime import date, timedelta

# ── Carrega .env.local ──────────────────────────────────────────
def load_env(path=".env.local"):
    if not os.path.exists(path):
        return
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            os.environ.setdefault(k.strip(), v.strip().strip('"').strip("'"))

load_env()

SUPABASE_URL = os.environ.get("NEXT_PUBLIC_SUPABASE_URL") or os.environ.get("SUPABASE_URL", "")
SUPABASE_KEY = (
    os.environ.get("SUPABASE_SERVICE_ROLE_KEY")
    or os.environ.get("SUPABASE_SERVICE_KEY", "")
)

if not SUPABASE_URL or not SUPABASE_KEY:
    raise SystemExit("❌ Configure NEXT_PUBLIC_SUPABASE_URL e SUPABASE_SERVICE_ROLE_KEY no .env.local")

# ── Helpers de data ─────────────────────────────────────────────
HOJE = date.today()

def d(offset: int) -> str:
    return (HOJE + timedelta(days=offset)).isoformat()

# ── Dados dos editais ───────────────────────────────────────────
# materias: array de strings com as disciplinas que caem na prova
# salario: salário base inicial
# salario_max: teto da carreira ou após progressão

EDITAIS = [

  # ── SEGURANÇA PÚBLICA FEDERAL ───────────────────────────────
  {
    "orgao": "Polícia Federal",
    "cargo": "Agente de Polícia Federal",
    "escolaridade": "superior",
    "nivel": "federal",
    "cidade": None,
    "estado": "Nacional",
    "area": "seguranca",
    "vagas": 1500,
    "salario": 14491.24,
    "salario_max": 22921.12,
    "banca": "Cebraspe",
    "data_inscricao_inicio": d(-15),
    "data_inscricao_fim": d(25),
    "data_prova": d(95),
    "link_inscricao": "https://www.gov.br/pf/pt-br/acesso-a-informacao/concursos",
    "link_edital_pdf": None,
    "materias": ["Língua Portuguesa", "Raciocínio Lógico", "Direito Constitucional",
                 "Direito Administrativo", "Direito Penal", "Direito Processual Penal",
                 "Legislação Especial", "Informática", "Estatística"],
    "status": "ativo",
  },
  {
    "orgao": "Polícia Federal",
    "cargo": "Delegado de Polícia Federal",
    "escolaridade": "superior",
    "nivel": "federal",
    "cidade": None,
    "estado": "Nacional",
    "area": "seguranca",
    "vagas": 192,
    "salario": 22455.18,
    "salario_max": 28500.00,
    "banca": "Cebraspe",
    "data_inscricao_inicio": d(-15),
    "data_inscricao_fim": d(25),
    "data_prova": d(120),
    "link_inscricao": "https://www.gov.br/pf/pt-br/acesso-a-informacao/concursos",
    "link_edital_pdf": None,
    "materias": ["Direito Constitucional", "Direito Administrativo", "Direito Penal",
                 "Direito Processual Penal", "Direito Civil", "Direito Tributário",
                 "Medicina Legal", "Criminologia", "Legislação Especial"],
    "status": "ativo",
  },
  {
    "orgao": "Polícia Rodoviária Federal (PRF)",
    "cargo": "Policial Rodoviário Federal",
    "escolaridade": "superior",
    "nivel": "federal",
    "cidade": None,
    "estado": "Nacional",
    "area": "seguranca",
    "vagas": 1000,
    "salario": 12522.50,
    "salario_max": 18000.00,
    "banca": "Cebraspe",
    "data_inscricao_inicio": d(-30),
    "data_inscricao_fim": d(10),
    "data_prova": d(80),
    "link_inscricao": "https://www.gov.br/prf/pt-br/acesso-a-informacao/concursos",
    "link_edital_pdf": None,
    "materias": ["Língua Portuguesa", "Legislação de Trânsito", "Direito Constitucional",
                 "Direito Administrativo", "Direito Penal", "Raciocínio Lógico", "Informática"],
    "status": "ativo",
  },
  {
    "orgao": "Departamento Penitenciário Nacional (DEPEN)",
    "cargo": "Agente Penitenciário Federal",
    "escolaridade": "medio",
    "nivel": "federal",
    "cidade": None,
    "estado": "Nacional",
    "area": "seguranca",
    "vagas": 513,
    "salario": 8025.27,
    "salario_max": 12500.00,
    "banca": "Cebraspe",
    "data_inscricao_inicio": d(5),
    "data_inscricao_fim": d(45),
    "data_prova": d(120),
    "link_inscricao": "https://www.gov.br/depen",
    "link_edital_pdf": None,
    "materias": ["Língua Portuguesa", "Raciocínio Lógico", "Direito Constitucional",
                 "Direito Administrativo", "Legislação Penitenciária"],
    "status": "ativo",
  },

  # ── RECEITA E FAZENDA ────────────────────────────────────────
  {
    "orgao": "Receita Federal do Brasil",
    "cargo": "Auditor-Fiscal da Receita Federal (AFRFB)",
    "escolaridade": "superior",
    "nivel": "federal",
    "cidade": None,
    "estado": "Nacional",
    "area": "tributario",
    "vagas": 699,
    "salario": 21029.09,
    "salario_max": 26000.00,
    "banca": "FGV",
    "data_inscricao_inicio": d(-5),
    "data_inscricao_fim": d(35),
    "data_prova": d(110),
    "link_inscricao": "https://www.gov.br/receitafederal/pt-br/acesso-a-informacao/concursos",
    "link_edital_pdf": None,
    "materias": ["Direito Tributário", "Direito Constitucional", "Direito Administrativo",
                 "Direito Previdenciário", "Contabilidade", "Economia", "Raciocínio Lógico",
                 "Língua Portuguesa", "Comércio Internacional"],
    "status": "ativo",
  },
  {
    "orgao": "Receita Federal do Brasil",
    "cargo": "Analista-Tributário da Receita Federal (ATRFB)",
    "escolaridade": "medio",
    "nivel": "federal",
    "cidade": None,
    "estado": "Nacional",
    "area": "tributario",
    "vagas": 469,
    "salario": 9635.42,
    "salario_max": 12000.00,
    "banca": "FGV",
    "data_inscricao_inicio": d(-5),
    "data_inscricao_fim": d(35),
    "data_prova": d(110),
    "link_inscricao": "https://www.gov.br/receitafederal/pt-br/acesso-a-informacao/concursos",
    "link_edital_pdf": None,
    "materias": ["Língua Portuguesa", "Raciocínio Lógico", "Matemática", "Direito Tributário",
                 "Direito Constitucional", "Direito Administrativo", "Informática"],
    "status": "ativo",
  },
  {
    "orgao": "Banco Central do Brasil (BACEN)",
    "cargo": "Analista (área: Tecnologia da Informação)",
    "escolaridade": "superior",
    "nivel": "federal",
    "cidade": "Brasília",
    "estado": "DF",
    "area": "tecnologia",
    "vagas": 50,
    "salario": 20937.84,
    "salario_max": 22000.00,
    "banca": "Cebraspe",
    "data_inscricao_inicio": d(10),
    "data_inscricao_fim": d(50),
    "data_prova": d(130),
    "link_inscricao": "https://www.bcb.gov.br/sobre/concursoseprocedimentos",
    "link_edital_pdf": None,
    "materias": ["Tecnologia da Informação", "Arquitetura de Software", "Segurança da Informação",
                 "Banco de Dados", "Língua Portuguesa", "Raciocínio Lógico", "Economia",
                 "Direito Administrativo"],
    "status": "ativo",
  },
  {
    "orgao": "Banco Central do Brasil (BACEN)",
    "cargo": "Analista (área: Economia e Finanças)",
    "escolaridade": "superior",
    "nivel": "federal",
    "cidade": "Brasília",
    "estado": "DF",
    "area": "tributario",
    "vagas": 40,
    "salario": 20937.84,
    "salario_max": 22000.00,
    "banca": "Cebraspe",
    "data_inscricao_inicio": d(10),
    "data_inscricao_fim": d(50),
    "data_prova": d(130),
    "link_inscricao": "https://www.bcb.gov.br/sobre/concursoseprocedimentos",
    "link_edital_pdf": None,
    "materias": ["Economia", "Finanças Públicas", "Macroeconomia", "Econometria",
                 "Direito Administrativo", "Língua Portuguesa", "Raciocínio Lógico"],
    "status": "ativo",
  },

  # ── TRIBUNAIS SUPERIORES ─────────────────────────────────────
  {
    "orgao": "Superior Tribunal de Justiça (STJ)",
    "cargo": "Analista Judiciário — Área Judiciária",
    "escolaridade": "superior",
    "nivel": "federal",
    "cidade": "Brasília",
    "estado": "DF",
    "area": "judiciario",
    "vagas": 20,
    "salario": 10600.00,
    "salario_max": 13500.00,
    "banca": "Cebraspe",
    "data_inscricao_inicio": d(-20),
    "data_inscricao_fim": d(5),
    "data_prova": d(75),
    "link_inscricao": "https://www.stj.jus.br/sites/portalp/Paginas/Concurso/Concurso.aspx",
    "link_edital_pdf": None,
    "materias": ["Língua Portuguesa", "Raciocínio Lógico", "Direito Constitucional",
                 "Direito Administrativo", "Direito Civil", "Direito Processual Civil",
                 "Direito Penal", "Direito Processual Penal"],
    "status": "ativo",
  },
  {
    "orgao": "Tribunal Superior Eleitoral (TSE)",
    "cargo": "Analista Judiciário — Análise de Sistemas",
    "escolaridade": "superior",
    "nivel": "federal",
    "cidade": "Brasília",
    "estado": "DF",
    "area": "judiciario",
    "vagas": 30,
    "salario": 10600.00,
    "salario_max": 13500.00,
    "banca": "FGV",
    "data_inscricao_inicio": d(15),
    "data_inscricao_fim": d(55),
    "data_prova": d(135),
    "link_inscricao": "https://www.tse.jus.br/institucional/concursos",
    "link_edital_pdf": None,
    "materias": ["Língua Portuguesa", "Raciocínio Lógico", "Tecnologia da Informação",
                 "Banco de Dados", "Direito Constitucional", "Direito Eleitoral",
                 "Arquitetura de Software", "Segurança da Informação"],
    "status": "ativo",
  },

  # ── TRFs ─────────────────────────────────────────────────────
  {
    "orgao": "Tribunal Regional Federal da 1ª Região (TRF1)",
    "cargo": "Analista Judiciário — Área Administrativa",
    "escolaridade": "superior",
    "nivel": "federal",
    "cidade": "Brasília",
    "estado": "DF",
    "area": "judiciario",
    "vagas": 45,
    "salario": 10600.00,
    "salario_max": 13500.00,
    "banca": "Cebraspe",
    "data_inscricao_inicio": d(20),
    "data_inscricao_fim": d(60),
    "data_prova": d(140),
    "link_inscricao": "https://portal.trf1.jus.br/portaltrf1/institucional/gestao-de-pessoas/concursos.htm",
    "link_edital_pdf": None,
    "materias": ["Língua Portuguesa", "Raciocínio Lógico", "Direito Constitucional",
                 "Direito Administrativo", "Administração Geral", "Informática"],
    "status": "ativo",
  },
  {
    "orgao": "Tribunal Regional Federal da 3ª Região (TRF3)",
    "cargo": "Analista Judiciário — Área Judiciária",
    "escolaridade": "superior",
    "nivel": "federal",
    "cidade": "São Paulo",
    "estado": "SP",
    "area": "judiciario",
    "vagas": 38,
    "salario": 10600.00,
    "salario_max": 13500.00,
    "banca": "FCC",
    "data_inscricao_inicio": d(-10),
    "data_inscricao_fim": d(20),
    "data_prova": d(100),
    "link_inscricao": "https://www.trf3.jus.br/trf3/index.php/concursos",
    "link_edital_pdf": None,
    "materias": ["Língua Portuguesa", "Raciocínio Lógico", "Direito Constitucional",
                 "Direito Administrativo", "Direito Civil", "Direito Processual Civil"],
    "status": "ativo",
  },
  {
    "orgao": "Tribunal Regional Federal da 4ª Região (TRF4)",
    "cargo": "Técnico Judiciário — Área Administrativa",
    "escolaridade": "medio",
    "nivel": "federal",
    "cidade": "Porto Alegre",
    "estado": "RS",
    "area": "judiciario",
    "vagas": 60,
    "salario": 7591.37,
    "salario_max": 9500.00,
    "banca": "FCC",
    "data_inscricao_inicio": d(5),
    "data_inscricao_fim": d(45),
    "data_prova": d(115),
    "link_inscricao": "https://www.trf4.jus.br/trf4/controlador.php?acao=pagina_visualizar&id_pagina=32",
    "link_edital_pdf": None,
    "materias": ["Língua Portuguesa", "Raciocínio Lógico", "Direito Constitucional",
                 "Direito Administrativo", "Informática"],
    "status": "ativo",
  },

  # ── TRTs ─────────────────────────────────────────────────────
  {
    "orgao": "Tribunal Regional do Trabalho da 2ª Região (TRT2)",
    "cargo": "Analista Judiciário — Área Judiciária",
    "escolaridade": "superior",
    "nivel": "federal",
    "cidade": "São Paulo",
    "estado": "SP",
    "area": "judiciario",
    "vagas": 55,
    "salario": 10600.00,
    "salario_max": 13500.00,
    "banca": "FCC",
    "data_inscricao_inicio": d(-25),
    "data_inscricao_fim": d(5),
    "data_prova": d(85),
    "link_inscricao": "https://www.trt2.jus.br/trt2/institucional/concursos",
    "link_edital_pdf": None,
    "materias": ["Língua Portuguesa", "Raciocínio Lógico", "Direito Constitucional",
                 "Direito Administrativo", "Direito do Trabalho", "Direito Processual do Trabalho"],
    "status": "ativo",
  },
  {
    "orgao": "Tribunal Regional do Trabalho da 4ª Região (TRT4)",
    "cargo": "Técnico Judiciário — Área Administrativa",
    "escolaridade": "medio",
    "nivel": "federal",
    "cidade": "Porto Alegre",
    "estado": "RS",
    "area": "judiciario",
    "vagas": 40,
    "salario": 7591.37,
    "salario_max": 9500.00,
    "banca": "FCC",
    "data_inscricao_inicio": d(12),
    "data_inscricao_fim": d(52),
    "data_prova": d(122),
    "link_inscricao": "https://www.trt4.jus.br/portais/trt4/montaDocumentos.do?action=loadPage&id_pagina=218",
    "link_edital_pdf": None,
    "materias": ["Língua Portuguesa", "Matemática", "Direito Constitucional",
                 "Direito Administrativo", "Direito do Trabalho", "Informática"],
    "status": "ativo",
  },

  # ── TCU / CGU ────────────────────────────────────────────────
  {
    "orgao": "Tribunal de Contas da União (TCU)",
    "cargo": "Analista de Controle Externo (ACE) — Área de Controle Externo",
    "escolaridade": "superior",
    "nivel": "federal",
    "cidade": "Brasília",
    "estado": "DF",
    "area": "administrativo",
    "vagas": 100,
    "salario": 10600.00,
    "salario_max": 18000.00,
    "banca": "Cebraspe",
    "data_inscricao_inicio": d(30),
    "data_inscricao_fim": d(70),
    "data_prova": d(150),
    "link_inscricao": "https://portal.tcu.gov.br/institucional/concursos/",
    "link_edital_pdf": None,
    "materias": ["Língua Portuguesa", "Raciocínio Lógico", "Direito Constitucional",
                 "Direito Administrativo", "Auditoria", "Contabilidade Pública",
                 "Controle Externo", "Finanças Públicas"],
    "status": "ativo",
  },
  {
    "orgao": "Controladoria-Geral da União (CGU)",
    "cargo": "Auditor Federal de Finanças e Controle (AFFC)",
    "escolaridade": "superior",
    "nivel": "federal",
    "cidade": "Brasília",
    "estado": "DF",
    "area": "administrativo",
    "vagas": 300,
    "salario": 19956.39,
    "salario_max": 22000.00,
    "banca": "Cebraspe",
    "data_inscricao_inicio": d(20),
    "data_inscricao_fim": d(60),
    "data_prova": d(140),
    "link_inscricao": "https://www.gov.br/cgu/pt-br/acesso-a-informacao/concursos",
    "link_edital_pdf": None,
    "materias": ["Língua Portuguesa", "Raciocínio Lógico", "Direito Constitucional",
                 "Direito Administrativo", "Auditoria Governamental", "Controle Interno",
                 "Finanças Públicas", "Contabilidade"],
    "status": "ativo",
  },

  # ── INSS ─────────────────────────────────────────────────────
  {
    "orgao": "Instituto Nacional do Seguro Social (INSS)",
    "cargo": "Técnico do Seguro Social",
    "escolaridade": "medio",
    "nivel": "federal",
    "cidade": None,
    "estado": "Nacional",
    "area": "administrativo",
    "vagas": 7893,
    "salario": 5905.79,
    "salario_max": 8000.00,
    "banca": "Cebraspe",
    "data_inscricao_inicio": d(-10),
    "data_inscricao_fim": d(20),
    "data_prova": d(90),
    "link_inscricao": "https://www.gov.br/inss/pt-br/acesso-a-informacao/concursos-publicos",
    "link_edital_pdf": None,
    "materias": ["Língua Portuguesa", "Matemática", "Raciocínio Lógico",
                 "Direito Administrativo", "Direito Previdenciário",
                 "Atendimento ao Público", "Informática"],
    "status": "ativo",
  },

  # ── AGÊNCIAS REGULADORAS ─────────────────────────────────────
  {
    "orgao": "Agência Nacional de Telecomunicações (ANATEL)",
    "cargo": "Especialista em Regulação de Telecomunicações",
    "escolaridade": "superior",
    "nivel": "federal",
    "cidade": "Brasília",
    "estado": "DF",
    "area": "tecnologia",
    "vagas": 80,
    "salario": 18872.34,
    "salario_max": 20000.00,
    "banca": "Cebraspe",
    "data_inscricao_inicio": d(25),
    "data_inscricao_fim": d(65),
    "data_prova": d(145),
    "link_inscricao": "https://www.gov.br/anatel/pt-br/acesso-a-informacao/concursos",
    "link_edital_pdf": None,
    "materias": ["Língua Portuguesa", "Raciocínio Lógico", "Telecomunicações",
                 "Direito Constitucional", "Direito Administrativo", "Regulação"],
    "status": "ativo",
  },
  {
    "orgao": "Agência Nacional de Energia Elétrica (ANEEL)",
    "cargo": "Especialista em Regulação de Serviços Públicos de Energia Elétrica",
    "escolaridade": "superior",
    "nivel": "federal",
    "cidade": "Brasília",
    "estado": "DF",
    "area": "tecnologia",
    "vagas": 60,
    "salario": 18872.34,
    "salario_max": 20000.00,
    "banca": "Cebraspe",
    "data_inscricao_inicio": d(40),
    "data_inscricao_fim": d(80),
    "data_prova": d(160),
    "link_inscricao": "https://www.gov.br/aneel/pt-br/acesso-a-informacao/concursos",
    "link_edital_pdf": None,
    "materias": ["Língua Portuguesa", "Raciocínio Lógico", "Engenharia Elétrica",
                 "Direito Constitucional", "Direito Administrativo", "Regulação de Energia"],
    "status": "ativo",
  },
  {
    "orgao": "Agência Nacional de Vigilância Sanitária (ANVISA)",
    "cargo": "Especialista em Regulação e Vigilância Sanitária",
    "escolaridade": "superior",
    "nivel": "federal",
    "cidade": "Brasília",
    "estado": "DF",
    "area": "saude",
    "vagas": 150,
    "salario": 14896.50,
    "salario_max": 16000.00,
    "banca": "Cebraspe",
    "data_inscricao_inicio": d(35),
    "data_inscricao_fim": d(75),
    "data_prova": d(155),
    "link_inscricao": "https://www.gov.br/anvisa/pt-br/acessoainformacao/rh/concursos",
    "link_edital_pdf": None,
    "materias": ["Língua Portuguesa", "Raciocínio Lógico", "Vigilância Sanitária",
                 "Direito Constitucional", "Direito Administrativo", "Saúde Pública"],
    "status": "ativo",
  },

  # ── PODER LEGISLATIVO ────────────────────────────────────────
  {
    "orgao": "Senado Federal",
    "cargo": "Analista Legislativo — Processo Legislativo",
    "escolaridade": "superior",
    "nivel": "federal",
    "cidade": "Brasília",
    "estado": "DF",
    "area": "administrativo",
    "vagas": 30,
    "salario": 25100.58,
    "salario_max": 30000.00,
    "banca": "FGV",
    "data_inscricao_inicio": d(45),
    "data_inscricao_fim": d(85),
    "data_prova": d(165),
    "link_inscricao": "https://www.senado.leg.br/institucional/concursos/",
    "link_edital_pdf": None,
    "materias": ["Língua Portuguesa", "Raciocínio Lógico", "Direito Constitucional",
                 "Ciência Política", "Processo Legislativo", "Direito Administrativo",
                 "Administração Pública"],
    "status": "ativo",
  },
  {
    "orgao": "Câmara dos Deputados",
    "cargo": "Analista Legislativo — Consultoria Legislativa (Área de Direito)",
    "escolaridade": "superior",
    "nivel": "federal",
    "cidade": "Brasília",
    "estado": "DF",
    "area": "judiciario",
    "vagas": 18,
    "salario": 24440.00,
    "salario_max": 29000.00,
    "banca": "Cebraspe",
    "data_inscricao_inicio": d(50),
    "data_inscricao_fim": d(90),
    "data_prova": d(170),
    "link_inscricao": "https://www2.camara.leg.br/a-camara/recursos-humanos/concursos",
    "link_edital_pdf": None,
    "materias": ["Direito Constitucional", "Direito Administrativo", "Direito Civil",
                 "Direito Penal", "Direito Tributário", "Processo Legislativo",
                 "Língua Portuguesa", "Raciocínio Lógico"],
    "status": "ativo",
  },

  # ── CORREIOS / INFRAESTRUTURA ────────────────────────────────
  {
    "orgao": "Empresa Brasileira de Correios e Telégrafos",
    "cargo": "Carteiro",
    "escolaridade": "medio",
    "nivel": "federal",
    "cidade": None,
    "estado": "Nacional",
    "area": "administrativo",
    "vagas": 3000,
    "salario": 2429.00,
    "salario_max": 3500.00,
    "banca": "Cebraspe",
    "data_inscricao_inicio": d(-5),
    "data_inscricao_fim": d(25),
    "data_prova": d(90),
    "link_inscricao": "https://www.correios.com.br/sobre-os-correios/nossa-empresa/concursos",
    "link_edital_pdf": None,
    "materias": ["Língua Portuguesa", "Matemática", "Raciocínio Lógico",
                 "Noções de Informática", "Atendimento ao Público"],
    "status": "ativo",
  },

  # ── SAÚDE / EBSERH ───────────────────────────────────────────
  {
    "orgao": "Empresa Brasileira de Serviços Hospitalares (EBSERH)",
    "cargo": "Analista Administrativo — Área: Administração",
    "escolaridade": "superior",
    "nivel": "federal",
    "cidade": None,
    "estado": "Nacional",
    "area": "saude",
    "vagas": 200,
    "salario": 4788.57,
    "salario_max": 7000.00,
    "banca": "AOCP",
    "data_inscricao_inicio": d(8),
    "data_inscricao_fim": d(48),
    "data_prova": d(118),
    "link_inscricao": "https://www.ebserh.gov.br/web/portal-ebserh/processo-seletivo",
    "link_edital_pdf": None,
    "materias": ["Língua Portuguesa", "Raciocínio Lógico", "Administração Geral",
                 "Administração Pública", "Direito Administrativo", "Informática"],
    "status": "ativo",
  },
  {
    "orgao": "Empresa Brasileira de Serviços Hospitalares (EBSERH)",
    "cargo": "Médico — Clínica Médica",
    "escolaridade": "superior",
    "nivel": "federal",
    "cidade": None,
    "estado": "Nacional",
    "area": "saude",
    "vagas": 120,
    "salario": 9600.00,
    "salario_max": 15000.00,
    "banca": "AOCP",
    "data_inscricao_inicio": d(8),
    "data_inscricao_fim": d(48),
    "data_prova": d(118),
    "link_inscricao": "https://www.ebserh.gov.br/web/portal-ebserh/processo-seletivo",
    "link_edital_pdf": None,
    "materias": ["Clínica Médica", "Urgência e Emergência", "Farmacologia",
                 "Saúde Coletiva", "Bioética"],
    "status": "ativo",
  },

  # ── POLÍCIA CIVIL ESTADUAL ───────────────────────────────────
  {
    "orgao": "Polícia Civil do Estado de São Paulo (PCSP)",
    "cargo": "Investigador de Polícia",
    "escolaridade": "medio",
    "nivel": "estadual",
    "cidade": "São Paulo",
    "estado": "SP",
    "area": "seguranca",
    "vagas": 2700,
    "salario": 4321.00,
    "salario_max": 7200.00,
    "banca": "Vunesp",
    "data_inscricao_inicio": d(-20),
    "data_inscricao_fim": d(10),
    "data_prova": d(80),
    "link_inscricao": "https://www.policiacivil.sp.gov.br/portal/concurso",
    "link_edital_pdf": None,
    "materias": ["Língua Portuguesa", "Raciocínio Lógico", "Direito Constitucional",
                 "Direito Administrativo", "Direito Penal", "Direito Processual Penal",
                 "Informática"],
    "status": "ativo",
  },
  {
    "orgao": "Polícia Civil do Estado de São Paulo (PCSP)",
    "cargo": "Delegado de Polícia",
    "escolaridade": "superior",
    "nivel": "estadual",
    "cidade": "São Paulo",
    "estado": "SP",
    "area": "seguranca",
    "vagas": 200,
    "salario": 13250.00,
    "salario_max": 19000.00,
    "banca": "Vunesp",
    "data_inscricao_inicio": d(-20),
    "data_inscricao_fim": d(10),
    "data_prova": d(100),
    "link_inscricao": "https://www.policiacivil.sp.gov.br/portal/concurso",
    "link_edital_pdf": None,
    "materias": ["Direito Constitucional", "Direito Administrativo", "Direito Penal",
                 "Direito Processual Penal", "Medicina Legal", "Criminologia",
                 "Direito Civil", "Direito Processual Civil"],
    "status": "ativo",
  },
  {
    "orgao": "Polícia Civil do Estado do Rio de Janeiro (PCERJ)",
    "cargo": "Inspetor de Polícia",
    "escolaridade": "medio",
    "nivel": "estadual",
    "cidade": "Rio de Janeiro",
    "estado": "RJ",
    "area": "seguranca",
    "vagas": 800,
    "salario": 4100.00,
    "salario_max": 6500.00,
    "banca": "FGV",
    "data_inscricao_inicio": d(10),
    "data_inscricao_fim": d(50),
    "data_prova": d(120),
    "link_inscricao": "https://www.pcerj.rj.gov.br",
    "link_edital_pdf": None,
    "materias": ["Língua Portuguesa", "Matemática", "Direito Constitucional",
                 "Direito Administrativo", "Direito Penal", "Direito Processual Penal"],
    "status": "ativo",
  },
  {
    "orgao": "Polícia Civil do Estado de Minas Gerais (PCMG)",
    "cargo": "Investigador de Polícia Civil",
    "escolaridade": "medio",
    "nivel": "estadual",
    "cidade": "Belo Horizonte",
    "estado": "MG",
    "area": "seguranca",
    "vagas": 1200,
    "salario": 4050.00,
    "salario_max": 6800.00,
    "banca": "Idecan",
    "data_inscricao_inicio": d(18),
    "data_inscricao_fim": d(58),
    "data_prova": d(128),
    "link_inscricao": "https://www.pc.mg.gov.br/concurso",
    "link_edital_pdf": None,
    "materias": ["Língua Portuguesa", "Raciocínio Lógico", "Direito Constitucional",
                 "Direito Administrativo", "Direito Penal", "Direito Processual Penal",
                 "Informática", "Atualidades"],
    "status": "ativo",
  },
  {
    "orgao": "Polícia Civil do Estado do Paraná (PCPR)",
    "cargo": "Delegado de Polícia Civil",
    "escolaridade": "superior",
    "nivel": "estadual",
    "cidade": "Curitiba",
    "estado": "PR",
    "area": "seguranca",
    "vagas": 90,
    "salario": 11500.00,
    "salario_max": 17000.00,
    "banca": "IBFC",
    "data_inscricao_inicio": d(22),
    "data_inscricao_fim": d(62),
    "data_prova": d(142),
    "link_inscricao": "https://www.policiacivil.pr.def.br/concursos",
    "link_edital_pdf": None,
    "materias": ["Direito Constitucional", "Direito Administrativo", "Direito Penal",
                 "Direito Processual Penal", "Medicina Legal", "Criminologia", "Direito Civil"],
    "status": "ativo",
  },

  # ── JUDICIÁRIO ESTADUAL ──────────────────────────────────────
  {
    "orgao": "Tribunal de Justiça do Estado de São Paulo (TJSP)",
    "cargo": "Escrevente Técnico Judiciário",
    "escolaridade": "medio",
    "nivel": "estadual",
    "cidade": "São Paulo",
    "estado": "SP",
    "area": "judiciario",
    "vagas": 1200,
    "salario": 4283.65,
    "salario_max": 6000.00,
    "banca": "Vunesp",
    "data_inscricao_inicio": d(-5),
    "data_inscricao_fim": d(30),
    "data_prova": d(100),
    "link_inscricao": "https://www.tjsp.jus.br/Concurso",
    "link_edital_pdf": None,
    "materias": ["Língua Portuguesa", "Matemática", "Raciocínio Lógico",
                 "Direito Constitucional", "Noções de Direito Penal",
                 "Noções de Direito Civil", "Informática"],
    "status": "ativo",
  },
  {
    "orgao": "Tribunal de Justiça do Estado de Minas Gerais (TJMG)",
    "cargo": "Analista Judiciário — Área Judiciária",
    "escolaridade": "superior",
    "nivel": "estadual",
    "cidade": "Belo Horizonte",
    "estado": "MG",
    "area": "judiciario",
    "vagas": 250,
    "salario": 8900.00,
    "salario_max": 12000.00,
    "banca": "Fundatec",
    "data_inscricao_inicio": d(28),
    "data_inscricao_fim": d(68),
    "data_prova": d(148),
    "link_inscricao": "https://www.tjmg.jus.br/portal-tjmg/institucional/concursos.htm",
    "link_edital_pdf": None,
    "materias": ["Língua Portuguesa", "Raciocínio Lógico", "Direito Constitucional",
                 "Direito Administrativo", "Direito Civil", "Direito Processual Civil"],
    "status": "ativo",
  },

  # ── MINISTÉRIO PÚBLICO ───────────────────────────────────────
  {
    "orgao": "Ministério Público do Estado de São Paulo (MP-SP)",
    "cargo": "Analista de Promotoria — Área: Informática",
    "escolaridade": "superior",
    "nivel": "estadual",
    "cidade": "São Paulo",
    "estado": "SP",
    "area": "tecnologia",
    "vagas": 35,
    "salario": 7450.00,
    "salario_max": 10000.00,
    "banca": "Vunesp",
    "data_inscricao_inicio": d(15),
    "data_inscricao_fim": d(55),
    "data_prova": d(125),
    "link_inscricao": "https://www.mpsp.mp.br/portal/page/portal/Ministerio_Publico/Concursos",
    "link_edital_pdf": None,
    "materias": ["Língua Portuguesa", "Raciocínio Lógico", "Tecnologia da Informação",
                 "Banco de Dados", "Redes de Computadores", "Segurança da Informação",
                 "Direito Administrativo"],
    "status": "ativo",
  },

  # ── PREFEITURAS ──────────────────────────────────────────────
  {
    "orgao": "Prefeitura Municipal de São Paulo",
    "cargo": "Agente Fiscal",
    "escolaridade": "medio",
    "nivel": "municipal",
    "cidade": "São Paulo",
    "estado": "SP",
    "area": "tributario",
    "vagas": 800,
    "salario": 4150.00,
    "salario_max": 6000.00,
    "banca": "Vunesp",
    "data_inscricao_inicio": d(-8),
    "data_inscricao_fim": d(22),
    "data_prova": d(95),
    "link_inscricao": "https://www.prefeitura.sp.gov.br/cidade/secretarias/gestao/concursos/",
    "link_edital_pdf": None,
    "materias": ["Língua Portuguesa", "Matemática", "Raciocínio Lógico",
                 "Legislação Municipal", "Ética no Serviço Público", "Informática"],
    "status": "ativo",
  },
  {
    "orgao": "Prefeitura Municipal do Rio de Janeiro",
    "cargo": "Auditor de Controle Interno",
    "escolaridade": "superior",
    "nivel": "municipal",
    "cidade": "Rio de Janeiro",
    "estado": "RJ",
    "area": "tributario",
    "vagas": 120,
    "salario": 8900.00,
    "salario_max": 12000.00,
    "banca": "FGV",
    "data_inscricao_inicio": d(32),
    "data_inscricao_fim": d(72),
    "data_prova": d(152),
    "link_inscricao": "https://prefeitura.rio/concursos/",
    "link_edital_pdf": None,
    "materias": ["Língua Portuguesa", "Raciocínio Lógico", "Direito Constitucional",
                 "Direito Administrativo", "Auditoria", "Contabilidade", "Finanças Públicas"],
    "status": "ativo",
  },
  {
    "orgao": "Prefeitura Municipal de Belo Horizonte",
    "cargo": "Assistente Administrativo",
    "escolaridade": "medio",
    "nivel": "municipal",
    "cidade": "Belo Horizonte",
    "estado": "MG",
    "area": "administrativo",
    "vagas": 500,
    "salario": 2750.00,
    "salario_max": 4200.00,
    "banca": "Idecan",
    "data_inscricao_inicio": d(3),
    "data_inscricao_fim": d(43),
    "data_prova": d(113),
    "link_inscricao": "https://prefeitura.pbh.gov.br/rh/concurso",
    "link_edital_pdf": None,
    "materias": ["Língua Portuguesa", "Matemática", "Raciocínio Lógico",
                 "Noções de Informática", "Ética no Serviço Público"],
    "status": "ativo",
  },
  {
    "orgao": "Prefeitura Municipal de Curitiba",
    "cargo": "Auditor Fiscal de Tributos Municipais",
    "escolaridade": "superior",
    "nivel": "municipal",
    "cidade": "Curitiba",
    "estado": "PR",
    "area": "tributario",
    "vagas": 60,
    "salario": 11200.00,
    "salario_max": 14000.00,
    "banca": "Fundatec",
    "data_inscricao_inicio": d(42),
    "data_inscricao_fim": d(82),
    "data_prova": d(162),
    "link_inscricao": "https://www.curitiba.pr.gov.br/conteudo/concursos-publicos/145",
    "link_edital_pdf": None,
    "materias": ["Língua Portuguesa", "Raciocínio Lógico", "Direito Constitucional",
                 "Direito Tributário", "Direito Administrativo", "Contabilidade",
                 "Legislação Tributária Municipal"],
    "status": "ativo",
  },

  # ── SABESP / INFRAESTRUTURA ESTADUAL ─────────────────────────
  {
    "orgao": "Companhia de Saneamento Básico do Estado de SP (SABESP)",
    "cargo": "Analista de Sistemas Júnior",
    "escolaridade": "superior",
    "nivel": "estadual",
    "cidade": "São Paulo",
    "estado": "SP",
    "area": "tecnologia",
    "vagas": 80,
    "salario": 7100.00,
    "salario_max": 11000.00,
    "banca": "FCC",
    "data_inscricao_inicio": d(-3),
    "data_inscricao_fim": d(37),
    "data_prova": d(107),
    "link_inscricao": "https://site.sabesp.com.br/site/interna/Default.aspx?secaoId=553",
    "link_edital_pdf": None,
    "materias": ["Língua Portuguesa", "Raciocínio Lógico", "Tecnologia da Informação",
                 "Banco de Dados", "Desenvolvimento de Software", "Legislação"],
    "status": "ativo",
  },

  # ── TECNOLOGIA / DATAPREV ────────────────────────────────────
  {
    "orgao": "Empresa de Tecnologia e Informações da Previdência (DATAPREV)",
    "cargo": "Analista de Tecnologia da Informação",
    "escolaridade": "superior",
    "nivel": "federal",
    "cidade": None,
    "estado": "Nacional",
    "area": "tecnologia",
    "vagas": 280,
    "salario": 9900.00,
    "salario_max": 14000.00,
    "banca": "Cebraspe",
    "data_inscricao_inicio": d(6),
    "data_inscricao_fim": d(46),
    "data_prova": d(116),
    "link_inscricao": "https://portal.dataprev.gov.br/concursos",
    "link_edital_pdf": None,
    "materias": ["Língua Portuguesa", "Raciocínio Lógico", "Tecnologia da Informação",
                 "Banco de Dados", "Segurança da Informação", "Redes", "Desenvolvimento"],
    "status": "ativo",
  },

  # ── EDUCAÇÃO ─────────────────────────────────────────────────
  {
    "orgao": "Prefeitura Municipal de São Paulo",
    "cargo": "Professor de Educação Infantil",
    "escolaridade": "superior",
    "nivel": "municipal",
    "cidade": "São Paulo",
    "estado": "SP",
    "area": "educacao",
    "vagas": 1800,
    "salario": 4300.00,
    "salario_max": 7200.00,
    "banca": "Vunesp",
    "data_inscricao_inicio": d(14),
    "data_inscricao_fim": d(54),
    "data_prova": d(124),
    "link_inscricao": "https://www.prefeitura.sp.gov.br/cidade/secretarias/educacao/concursos/",
    "link_edital_pdf": None,
    "materias": ["Língua Portuguesa", "Conhecimentos Pedagógicos", "Legislação Educacional",
                 "Didática", "Psicologia da Educação", "Raciocínio Lógico"],
    "status": "ativo",
  },
  {
    "orgao": "Secretaria de Estado de Educação de Minas Gerais (SEE-MG)",
    "cargo": "Analista de Educação Básica",
    "escolaridade": "superior",
    "nivel": "estadual",
    "cidade": "Belo Horizonte",
    "estado": "MG",
    "area": "educacao",
    "vagas": 400,
    "salario": 4500.00,
    "salario_max": 7000.00,
    "banca": "Idecan",
    "data_inscricao_inicio": d(26),
    "data_inscricao_fim": d(66),
    "data_prova": d(146),
    "link_inscricao": "https://see.mg.gov.br/concursos",
    "link_edital_pdf": None,
    "materias": ["Língua Portuguesa", "Raciocínio Lógico", "Conhecimentos Pedagógicos",
                 "Legislação Educacional", "Gestão Escolar"],
    "status": "ativo",
  },

  # ── TCE ESTADUAIS ────────────────────────────────────────────
  {
    "orgao": "Tribunal de Contas do Estado de São Paulo (TCESP)",
    "cargo": "Agente da Fiscalização Financeira — Administração",
    "escolaridade": "superior",
    "nivel": "estadual",
    "cidade": "São Paulo",
    "estado": "SP",
    "area": "administrativo",
    "vagas": 25,
    "salario": 11900.00,
    "salario_max": 15000.00,
    "banca": "Vunesp",
    "data_inscricao_inicio": d(38),
    "data_inscricao_fim": d(78),
    "data_prova": d(158),
    "link_inscricao": "https://www.tce.sp.gov.br/concursos",
    "link_edital_pdf": None,
    "materias": ["Língua Portuguesa", "Raciocínio Lógico", "Direito Constitucional",
                 "Direito Administrativo", "Contabilidade Pública", "Auditoria",
                 "Controle Externo", "Administração Pública"],
    "status": "ativo",
  },

  # ── CONSELHO FEDERAL ─────────────────────────────────────────
  {
    "orgao": "Conselho Federal de Medicina (CFM)",
    "cargo": "Analista Administrativo",
    "escolaridade": "superior",
    "nivel": "federal",
    "cidade": "Brasília",
    "estado": "DF",
    "area": "saude",
    "vagas": 40,
    "salario": 5800.00,
    "salario_max": 9000.00,
    "banca": "Instituto Quadrix",
    "data_inscricao_inicio": d(16),
    "data_inscricao_fim": d(56),
    "data_prova": d(126),
    "link_inscricao": "https://portal.cfm.org.br/concurso",
    "link_edital_pdf": None,
    "materias": ["Língua Portuguesa", "Raciocínio Lógico", "Direito Administrativo",
                 "Administração Geral", "Informática"],
    "status": "ativo",
  },
  {
    "orgao": "Conselho Federal de Contabilidade (CFC)",
    "cargo": "Analista — Área de Tecnologia",
    "escolaridade": "superior",
    "nivel": "federal",
    "cidade": "Brasília",
    "estado": "DF",
    "area": "tecnologia",
    "vagas": 20,
    "salario": 6200.00,
    "salario_max": 9500.00,
    "banca": "Instituto Quadrix",
    "data_inscricao_inicio": d(33),
    "data_inscricao_fim": d(73),
    "data_prova": d(153),
    "link_inscricao": "https://cfc.org.br/concurso",
    "link_edital_pdf": None,
    "materias": ["Língua Portuguesa", "Raciocínio Lógico", "Tecnologia da Informação",
                 "Segurança da Informação", "Banco de Dados", "Direito Administrativo"],
    "status": "ativo",
  },

  # ── FORÇAS ARMADAS / MILITARES ───────────────────────────────
  {
    "orgao": "Marinha do Brasil",
    "cargo": "Fuzileiro Naval — Praças",
    "escolaridade": "medio",
    "nivel": "federal",
    "cidade": None,
    "estado": "Nacional",
    "area": "seguranca",
    "vagas": 900,
    "salario": 2100.00,
    "salario_max": 4500.00,
    "banca": "Marinha do Brasil",
    "data_inscricao_inicio": d(-12),
    "data_inscricao_fim": d(18),
    "data_prova": d(75),
    "link_inscricao": "https://www.marinha.mil.br/concursos",
    "link_edital_pdf": None,
    "materias": ["Língua Portuguesa", "Matemática", "Ciências", "Inglês"],
    "status": "ativo",
  },

  # ── IBGE / PESQUISA ──────────────────────────────────────────
  {
    "orgao": "Instituto Brasileiro de Geografia e Estatística (IBGE)",
    "cargo": "Agente de Pesquisas e Mapeamento",
    "escolaridade": "medio",
    "nivel": "federal",
    "cidade": None,
    "estado": "Nacional",
    "area": "administrativo",
    "vagas": 3500,
    "salario": 2100.00,
    "salario_max": 3200.00,
    "banca": "Cebraspe",
    "data_inscricao_inicio": d(-18),
    "data_inscricao_fim": d(2),
    "data_prova": d(60),
    "link_inscricao": "https://www.ibge.gov.br/acesso-informacao/institucional/concursos.html",
    "link_edital_pdf": None,
    "materias": ["Língua Portuguesa", "Matemática", "Raciocínio Lógico", "Noções de Informática"],
    "status": "ativo",
  },

  # ── EXTRA: SUFRAMA / NORTE ───────────────────────────────────
  {
    "orgao": "Superintendência da Zona Franca de Manaus (SUFRAMA)",
    "cargo": "Analista de Comércio Exterior",
    "escolaridade": "superior",
    "nivel": "federal",
    "cidade": "Manaus",
    "estado": "AM",
    "area": "tributario",
    "vagas": 45,
    "salario": 9500.00,
    "salario_max": 12000.00,
    "banca": "IBADE",
    "data_inscricao_inicio": d(44),
    "data_inscricao_fim": d(84),
    "data_prova": d(164),
    "link_inscricao": "https://www.suframa.gov.br/concursos",
    "link_edital_pdf": None,
    "materias": ["Língua Portuguesa", "Raciocínio Lógico", "Comércio Exterior",
                 "Direito Tributário", "Direito Administrativo", "Economia"],
    "status": "ativo",
  },
]

# ── Upsert via REST ─────────────────────────────────────────────
def upsert(edital: dict) -> bool:
    payload = {k: v for k, v in edital.items() if v is not None}
    # materias como JSON array
    if "materias" in payload:
        payload["materias"] = payload["materias"]  # já é lista Python — será serializada
    body = json.dumps(payload).encode()
    req = urllib.request.Request(
        f"{SUPABASE_URL}/rest/v1/editais",
        data=body,
        headers={
            "apikey": SUPABASE_KEY,
            "Authorization": f"Bearer {SUPABASE_KEY}",
            "Content-Type": "application/json",
            "Prefer": "resolution=merge-duplicates",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req) as resp:
            return resp.status in (200, 201)
    except urllib.error.HTTPError as e:
        err = e.read().decode()
        print(f"    HTTP {e.code}: {err[:300]}")
        return False

# ── Execução ────────────────────────────────────────────────────
print(f"🚀 Seed de editais — O Tutor")
print(f"📅 Datas relativas a: {HOJE.isoformat()}")
print(f"📦 {len(EDITAIS)} editais para inserir\n")

ok = erro = 0
for edital in EDITAIS:
    vagas = f"{edital['vagas']:,} vagas" if edital.get("vagas") else "vagas n/d"
    salario = f"R$ {edital['salario']:,.2f}" if edital.get("salario") else ""
    local = f"{edital['cidade']}/{edital['estado']}" if edital.get("cidade") else edital.get("estado", "")
    if upsert(edital):
        ok += 1
        print(f"  ✓ [{edital['nivel'][:3].upper()}] {edital['orgao']}")
        print(f"       {edital['cargo']} | {vagas} | {salario} | {local} | {edital['banca']}")
    else:
        erro += 1
        print(f"  ✗ {edital['orgao']} — {edital['cargo']}")

print(f"\n{'='*60}")
print(f"  ✅ Inseridos: {ok}   ❌ Erros: {erro}   📦 Total: {len(EDITAIS)}")
print(f"{'='*60}")
